// Generated by CoffeeScript 1.4.0
(function() {
  var $, Line, Marker, Text, placeMarker;

  $ = jQuery;

  $.fn.image_tag = function(options) {
    var settings;
    settings = $.extend({}, options);
    return this.on('mousedown', 'img', placeMarker);
  };

  placeMarker = function(e) {
    var body, globalDiv, line, marker;
    console.log(e);
    body = $('body');
    globalDiv = $('<div></div>');
    console.log(globalDiv);
    marker = new Marker(globalDiv, e.pageX, e.pageY);
    line = new Line(globalDiv, e.pageX + 8, e.pageY + 3);
    body.append(globalDiv);
    body.on('mousemove', function(e) {
      var css;
      css = {};
      css.width = Math.abs(e.pageX - line.x + 1);
      if (e.pageX + 8 < line.x) {
        css.left = e.pageX;
        css.width = Math.abs(e.pageX - line.x) - 7;
      }
      return line.line.css(css);
    });
    return body.on('mouseup', function(e) {
      var text;
      text = {};
      if (e.pageX < marker.x) {
        text = new Text(globalDiv, e.pageX - 100 - 9, marker.y, marker, line);
      } else {
        text = new Text(globalDiv, e.pageX, marker.y, marker, line);
      }
      body.off('mouseup');
      return body.off('mousemove');
    });
  };

  Line = (function() {

    function Line(div, x, y) {
      this.line = $('<div class="image-tag-line" id="image-tag-line-' + x + '+' + y + '"></div>');
      this.x = x;
      this.y = y;
      this.line.css({
        left: x + 'px',
        top: y + 'px'
      });
      div.append(this.line);
    }

    return Line;

  })();

  Marker = (function() {

    function Marker(div, x, y) {
      this.marker = $('<div class="image-tag-marker" id="image-tag-marker-' + x + '+' + y + '"></div>');
      this.x = x;
      this.y = y;
      this.marker.css({
        left: x + 'px',
        top: y + 'px'
      });
      div.append(this.marker);
    }

    return Marker;

  })();

  Text = (function() {

    function Text(div, x, y, marker, line) {
      this.line = line;
      this.marker = marker;
      this.text = $('<p class="image-tag-text" id="image-tag-text-' + x + '+' + y + '"></p>');
      this.text.css({
        left: x + 'px',
        top: y + 'px'
      });
      $(div).append(this.text);
      this.text.prop('contentEditable', true);
      this.text.on('keypress', function(e) {
        if (e.keyCode === 13) {
          $(this).prop('contentEditable', false);
          return $(this).blur();
        }
      });
      this.text.on('blur', function(e) {
        if ($.trim($(this).text()) === '') {
          $(this).remove();
          line.line.remove();
          return marker.marker.remove();
        }
      });
      this.text.focus();
    }

    return Text;

  })();

}).call(this);
